plugins {
    id 'com.android.application'
}

android {
    namespace 'jp.hamasho.bettei'
    compileSdk 35

    defaultConfig {
        applicationId 'jp.hamasho.bettei'
        minSdk 26
        targetSdk 35
        versionCode 21
        versionName '1.0.6-reservation-choice'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
